source ~/.config/vim/dotq/base.vim

filetype off				" required
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

source ~/.config/vim/dotq/plugins.vim
silent! source ~/.vim/local.vim

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

source ~/.config/vim/dotq/tags.vim
"source ~/.config/vim/dotq/unite.vim
