Plugin 'ervandew/supertab'
Plugin 'Shougo/unite.vim'
Plugin 'Shougo/vimfiler.vim'
Plugin 'ujihisa/unite-colorscheme'
Plugin 'osyo-manga/unite-quickfix'
Plugin 'bling/vim-airline'
Plugin 'tsukkee/unite-tag'
Plugin 'dag/vim-fish'
